### ISSUE TITLE
Insufficient explanation Lecture 2, slide 8

### ISSUE THREAD

**Issue by eatam23** [upb-lea/reinforcement_learning_course_materials#12]
In  Lecture 2, slide 8, it is not explained how P_{xx'}^m  in eq.(2.3) can be replaced  by a constant transition matrix as m goes to infinity. It is clear that as m goes to infinity p_{k+m} and p_{k}   in eq.(2.3) can be replaced by a constant matrix p, but not clear and not explained how P_{xx'}^m   becomes  P_{xx'}.

**Comment by wallscheid** [comment]
In steady state, the probability vector p_{k+1} and p_{k} must be equal (no probability change between two time steps). 

(2.4) represents (2.3) for m=1 and any k>1 in the steady state. 

Hope that helps.

**Comment by wallscheid** [comment]
As there seems to be no further comment, I'm closing this issue for now
