### ISSUE TITLE
Lecture 2, slide 28: inconsistent notation

### ISSUE THREAD

**Issue by eatam23** [upb-lea/reinforcement_learning_course_materials#14]
in eqs (2.14) and (2.15) "u_k" must me "u " and "x_k" must be "x" to be consistent with the notation used in the  rest of the equations.

**Comment by wallscheid** [comment]
In previous slides the short notation x_k+1 = x' and x_k=x was already used / introduced. Against this background, I do not identify any inconsistency within the mentioned equations.

Of course, the notation on this particular slide could be made more compact by leaving out the time index representation, but this is more of a style question.

**Comment by wallscheid** [comment]
As there seems to be no further comment, I'm closing this issue for now
