### ISSUE TITLE
Missed steps in going from Eq.3 to Eq.3.12

### ISSUE THREAD

**Issue by eatam23** [upb-lea/reinforcement_learning_course_materials#16]
It  will be helpful to put intermediate steps to show how  Eq.3.12 is obtained from Eq.3.

**Comment by wallscheid** [comment]
There are not really any steps missing, as the Richardson iteration is just applied to the Bellman equation. To clearify that, the slide has been modified to point out which particular version of the Bellman equation have been processed via the Richardson iteration.
