### ISSUE TITLE
Eligibility traces for SARSA(lambda)

### ISSUE THREAD

**Issue by MarvinMeyer** [upb-lea/reinforcement_learning_course_materials#17]
In Lecture 6 in the definition of the TD($\lambda$) update on Slide 30, the definition needs to be adjusted. On the one hand it should be "SARSA($\lambda$)" , on the other hand the Eligibility trace must be adjusted by the action: $z_k(x_k, a_k)$. 

Quellen:
Reinforcement Learning: An Introduction (Second Edition), Chapter 7.5 p. 183ff

**Comment by hvater** [comment]
I agree.

Additionally, it should be clarified that all q-values (i.e. the q-value for each possible state action combination) are updated in each iteration. It is a bit difficult to understand this from the current slide set.

For this, I propose to add an algorithm slide for SARSA(lambda) to Lecture 6. 
I will add this to the [fork](https://github.com/hvater/reinforcement_learning_course_materials) in which [XyDrKRulof](https://github.com/XyDrKRulof) and I are currently revising the exercises (and also reworked the task for the eligibility traces)  and we will create a pull request once it the work on the exercises.

**Comment by XyDrKRulof** [comment]
Fixed with pull request #20
