### ISSUE TITLE
Tidy up tutorial solution notebooks and provide problem templates 

### ISSUE THREAD

**Issue by wallscheid** [upb-lea/reinforcement_learning_course_materials#2]
* Some of the solution notebooks are not well readable. It seems that they partly contain debug column of figures or a bulk of number arrays floating around. There is still some room for improvement here to promote readability and a quick introduction to the topic.
* It would be nice to have a small mark down information sheet per tutorial summarizing the most important information (very short description of the adressed problems, used algorithms, maybe an overview of the sub-tasks within the notebook). The format of the mark down sheet should be standardized among all tutorials.
* And finally, please provide the task templates with gaps for the student inputs. Hence, for every notebook there should be two files like ex00_task_template.ipynb and ex00_solution.ipynb.
  * Question/remark: Is there maybe a straightforward way to automate the generation of the task template notebooks based on the solution notebooks (e.g. simplified / light nbgrader with Travis backend which erases parts of the solution code based on built-in keywords).   Investing once the effort in order to automate this pipeline will be very convinient for future updates of the tasks.

**Comment by wkirgsn** [comment]
Generation of "emptied" solution files that act as templates is perfectly possible with nbgrader, just enclosing stuff that needs to be hidden with "### BEGIN SOLUTION" and "# END SOLUTION".

Not sure what happens with travis-generated content, though. I think it can be commited next to the solution files with a small script in travis, then we would have a travis commit after each of our commits

**Comment by Webbah** [comment]
Does the enclosing works also for markdown? 
If not, how do we mark solutions there?

**Comment by wkirgsn** [comment]
Ok this is the instruction list:

1. Install nbgrader with
```
conda install jupyter
conda install -c conda-forge nbgrader
```
(do not use pip!)

2. Get the folder structure right, such that nbgrader can work:
   * exercises/
     * nbgrader_config.py  # configuration
     * templates/  # destination for autogenerated templates
     * solutions/  # actual source code (solutions with markers)
        * ex1/
        * ex2/
        ...

3. For each exercise solution notebook:
   * Open the notebook and click on `View` > `Cell toolbar` > `Create Assignment`
      * This enables assigning types and points to each cell
   * Mark task templates with "read-only", solution markdown with "manually graded answer", and solution code with "autograded answer", where solution lines are enclosed with `### BEGIN SOLUTION` and `### END SOLUTION`.

4. Generate the template from the solution with `nbgrader generate_assignment "<<exercise name>>"`, 
e.g. ```nbgrader generate_assignment "ex01"```


I can go ahead and start with point 2 but I will need assistance for point 3 and all exercises except 1 and 8.
The generation of the templates (point 4) from the solutions can be outsourced to TravisCI as soon as we have 1-3 finished.

**Comment by wkirgsn** [comment]
all templates are generated and readmes were created.
