### ISSUE TITLE
Representation error in the task sheet 3 (template and solution)

### ISSUE THREAD

**Issue by wallscheid** [upb-lea/reinforcement_learning_course_materials#3]
Some formulas are not correctly depicted at the start of both the template and solution notebook, cf.:

![grafik](https://user-images.githubusercontent.com/56304296/113250804-77bab400-92c1-11eb-8c65-5cfd2c7cae78.png)

**Comment by max-schenke** [comment]
This seems to be a github-related problem, the formulas still render nicely when opened in jupyter. I am on it and will see what I can.

Screenshot from jupyter:

![grafik](https://user-images.githubusercontent.com/61693487/113266355-785d4580-92d5-11eb-8f1f-f26fbda3b044.png)

**Comment by max-schenke** [comment]
Got formula rendering to work also on github, but the backend toolchain broke somehow (and to me it seems that this happened on an unrelated file). Build is failing right now.

![grafik](https://user-images.githubusercontent.com/61693487/113269015-52857000-92d8-11eb-8036-eeaff71847ae.png)

**Comment by wkirgsn** [comment]
travis ci pipeline is currently worked on. There seems to be a problem in texlive installation, but this is unrelated to this issue

**Comment by wallscheid** [comment]
nicely done!
