### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by VikasChidananda** [upb-lea/reinforcement_learning_course_materials#4]
Lecture 1, slide 36: I think it should be 'an MDP' instead of 'a MDP'. 
e.g. 1: "An MDP defines a stochastic control problem" 
(slide 8 on https://www.ccs.neu.edu/home/rplatt/cs5335_fall2017/slides/mdps.pdf )
e.g. 2: "In Mathematics, a Markov Decision Process ..."
(https://en.wikipedia.org/wiki/Markov_decision_process)

**Comment by wallscheid** [comment]
yes thanks, indeed there have been typos. updated slides are now available.
