### ISSUE TITLE
Exercise 4: cannot find Racetrack Environment

### ISSUE THREAD

**Issue by stwerner97** [upb-lea/reinforcement_learning_course_materials#5]
**Describe the bug**
In Exercise 04 Monte-Carlo methods should be implemented for the racetrack environment, however, I cannot find where ``racetrack_environment.py`` is located. Could you provide installation instructions or an description of the environment (e.g. ``env.yml`` for conda) to be used?

**Comment by wallscheid** [comment]
thanks for the hint, the environment was indeed missing. It seems that it was not transfered while we moved the repo from gitlab to github, but was now added.
